version: '3.7'
services:
  db:
    container_name: smartosc_mysql
    image: mysql:5.7
    ports: ['3306:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
  php:
    container_name: smartosc_php
    build: ./docker/php
    ports: ['9000:9001']
    links:
      - db
    volumes:
      - .:/var/www/smartosc:cached
    environment:
      SSH_AUTH_SOCK: /ssh-agent

  nginx:
    container_name: smartosc_nginx
    build: ./docker/nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./docker/nginx/logs:/var/log/nginx:cached
      - .:/var/www/smartosc:cached
